// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ocseqrqygsiqpsbjditl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9jc2VxcnF5Z3NpcXBzYmpkaXRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMzIzNDIsImV4cCI6MjA3MDYwODM0Mn0.fCf5K4VfJkoTshZgjSwmiOnIA3RYhPeiGZ_kFB43-AI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});